Add files via upload

diff --git a/.github/workflows/build-kernel-release-Next-Sukisu.yml b/.github/workflows/build-kernel-release-Next-Sukisu.yml
--- a/.github/workflows/build-kernel-release-Next-Sukisu.yml
+++ b/.github/workflows/build-kernel-release-Next-Sukisu.yml
@@ -171,34 +171,26 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Determine the branch for KernelSU-${{ inputs.kernelsu_variant }}
-        if: ${{ inputs.kernelsu_branch == 'Dev' || inputs.kernelsu_variant == 'SukiSU' }}
+        if: ${{ inputs.kernelsu_variant == 'SukiSU' || inputs.kernelsu_variant == 'Next' || inputs.kernelsu_branch == 'Other' }}
         run: |
-          # Determine the branch based on user input
-          if [[ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]]; then
-            BRANCH="main"
-          elif [[ "${{ inputs.kernelsu_branch }}" == "Other" && -n "${{ inputs.kernelsu_branch_other }}" ]]; then
-            BRANCH="${{ inputs.kernelsu_branch_other }}"
-          else
-            echo "Error: Custom branch not provided for 'Other'" >&2
-            exit 1
-          fi
-
-        if: ${{ inputs.kernelsu_variant == 'Next' || inputs.kernelsu_branch == 'Other' }}
-        run: |
-  # Determine the branch based on user input
-            if [[ "${{ inputs.kernelsu_variant }}" == "Next" ]]; then
+        # Determine the branch based on user input
+            if [[ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]]; then
                 BRANCH="main"
-            elif [[ "${{ inputs.kernelsu_branch }}" == "Other" && -n "${{ inputs.kernelsu_branch_other }}" ]]; then
-                BRANCH="${{ inputs.kernelsu_branch_other }}"
-            else
-                echo "Error: kernelsu_branch_other is required when branch is Other" >&2
-            exit 1
+            elif [[ "${{ inputs.kernelsu_variant }}" == "Next" ]]; then
+                BRANCH="main"
+            elif [[ "${{ inputs.kernelsu_branch }}" == "Other" ]]; then
+                if [[ -z "${{ inputs.kernelsu_branch_other }}" ]]; then
+                    echo "Error: kernelsu_branch_other is required when branch is Other" >&2
+                exit 1
             fi
+            BRANCH="${{ inputs.kernelsu_branch_other }}"
+        else
+            echo "Error: Unsupported KernelSU configuration" >&2
+        exit 1
+        fi
 
-            echo "Using branch: $BRANCH"
-          
-          # Store the selected branch in GITHUB_ENV
-          echo "KSU_BRANCH=$BRANCH" >> $GITHUB_ENV
+        echo "Using branch: $BRANCH"
+        echo "KSU_BRANCH=$BRANCH" >> "$GITHUB_ENV"
 
       - name: Get commit hash or tag and generate URL for KernelSU-${{ inputs.kernelsu_variant }}
         run: |
